### LOGIN BASIC (should not work here because of CSRF protection)
POST http://127.0.0.1:8000/api/login/
Authorization: Basic testingbackends@gandi.net:notverycommon

### LOGIN TOKEN (returns auth_token)
POST http://127.0.0.1:8000/api/token/login/
Content-Type: application/json

{
    "email": "testingbackends@gandi.net",
    "password": "notverycommon"
}

### LOGOUT
POST http://127.0.0.1:8000/api/token/logout/
Authorization: Token e09af1e9db76f413f91e0ac88c1be8c9bc53281c


### SESSION (should react false here)
GET http://127.0.0.1:8000/api/session/


### REGISTRATION
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "email": "testingbackends@gandi.net",
    "password": "notverycommon",
    "re_password": "notverycommon"
}


### /api/
GET http://127.0.0.1:8000/api/
Authorization: Token e09af1e9db76f413f91e0ac88c1be8c9bc53281c

### /api/users/
GET http://127.0.0.1:8000/api/users/
Authorization: Token e09af1e9db76f413f91e0ac88c1be8c9bc53281c
